name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout latest code  
      - name: Checkout latest code
        uses: actions/checkout@v4

      # setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Create .env for React frontend pointing to EC2
      - name: Setup React environment
        run: |
          echo "REACT_APP_API_BASE=http://${{ secrets.EC2_HOST }}:5000" > frontend/.env

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: CI=false npm run build

      # Verify build folder exists
      - name: List frontend build
        run: ls -R ./frontend/build

      # Copy backend + frontend build to EC2
      - name: Copy backend and frontend build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: /home/ec2-user/projects/myapp

      # Restart Flask app on EC2 using Gunicorn
      - name: Restart Flask app on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              cd /home/ec2-user/projects/myapp
              echo "API_KEY=${{ secrets.API_KEY }}" > .env
              cd backend
              echo "RESET_PASSWORD=purduepete" > .env
              echo "ENVIRONMENT=Prod" >> .env
              echo "API_KEY=${{ secrets.API_KEY }}" >> .env
              sudo systemctl stop myapp || true
              source ../venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
              sudo systemctl daemon-reload
              sudo systemctl start myapp
